CREATE TABLE [TB_FILMES] (
    Id INT PRIMARY KEY IDENTITY,
    Titulo NVARCHAR(100) NOT NULL,
    Diretor NVARCHAR(100) NOT NULL,
    AnoLancamento NVARCHAR(10) NOT NULL,
    Classificacao NVARCHAR(50) NOT NULL,
    Genero NVARCHAR(50) NOT NULL
);
